# This AnalysisTemplate will run a Kubernetes Job every 5 seconds that succeeds.
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: endpoint-reachable
spec:
  metrics:
  - name: endpoint-reachable
    count: 1
    interval: 5s
    failureLimit: 0
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: wbitt/network-multitool
                command:
                   - /bin/sh
                   - -c
                   - |
                      curl -I https://{{ .Values.analysis.url }}
                      status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "https://{{ .Values.analysis.url }}");
                      [ $status_code -eq 200 ]
              restartPolicy: Never
          backoffLimit: 0